-
  name: 'Update Auth and Roles on teleport'
  hosts: localhost
  connection: local

  tasks:

    # GITLAB Auth: GET variables from aws
    - name : "GET {{ env }} client_id from aws"
      debug:
        msg: '{{ lookup("aws_ssm", "{{ env }}_teleport_github_client_id") }}'
      register: client_id

    - name : "GET {{ env }} client_secret from aws"
      debug:
        msg: '{{ lookup("aws_ssm", "{{ env }}_teleport_github_client_secret") }}'
      register: client_secret
      
    - name : "GET {{ env }} redirect_url from aws"
      debug:
        msg: '{{ lookup("aws_ssm", "{{ env }}_teleport_github_redirect_url") }}'
      register: redirect_url


    # GITLAB Auth: Create yml file from template and inventory/ENV/auth.yml
    - name: SET variables in github template
      template: 
        src: templates/github.yml.j2
        dest: output/github.yml

    - name: GET auth config file for github
      ansible.builtin.include_vars:
        file: inventory/{{env}}/auth.yml
        name: auth

    - name: GET Github YAML
      ansible.builtin.include_vars:
        file: output/github.yml
        name: github

    - name: Merge auth and github
      ansible.builtin.set_fact:
        merged_vars: "{{ auth|combine(github, recursive=True) }}"

    - name: create yaml file in output
      ansible.builtin.copy:
        content: "{{ merged_vars | to_nice_yaml }}"
        dest: output/github.yml


    # GITLAB Auth: UPDATE GITLAB Auth on teleport
    - name: Update Github Auth
      ansible.builtin.command: "tctl create -f output/github.yml"



    # ROLES: UPDATE ROLES on teleport
    - name: GET all role names in array, key=metadata.name
      shell: tctl get roles --format=json | jq -r '.[].metadata.name'
      register: roles

    - name: delete all roles except access and editor
      ansible.builtin.command: "tctl rm roles/{{ item }}"
      loop: "{{ roles.stdout_lines }}"
      when: item != 'access' and item != 'editor'

    - name: Create roles from yml
      ansible.builtin.command: "tctl create -f inventory/roles.yml"

    - name: blank github file
      ansible.builtin.copy:
        content: ""
        dest: output/github.yml